dependencies:
  - python==3.11
  - pip
  - pip:
      - numpy<2.0.0
      - matplotlib
      - git+https://github.com/tedjohnson12/polar-disk-freq.git@main
      - rebound
      - reboundx
      - tqdm
      - scipy